# Generated by Django 6.0.6 on 2026-06-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.CharField(max_length=300)),
                ('product_price', models.FloatField()),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Ord',
        ),
    ]
