# Generated by Django 6.0.6 on 2026-06-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_order_delete_ord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_image',
        ),
    ]
