# Generated by Django 6.0.6 on 2026-06-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_order_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_image',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='order confirmed', max_length=20),
        ),
    ]
