# Generated by Django 6.0.6 on 2026-07-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_order_product_image_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_image',
            field=models.ImageField(default='', max_length=500, upload_to=''),
        ),
    ]
